FROM node:18-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:18
WORKDIR /app
COPY --from=build /app/package.json package.json
COPY --from=build /app/package-lock.json package-lock.json
COPY --from=build /app/dist dist
RUN npm install --production
ENV PORT=5000
EXPOSE 5000
CMD ["lambda.handler"]