FROM public.ecr.aws/lambda/nodejs:18 as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM public.ecr.aws/lambda/nodejs:18
WORKDIR ${LAMBDA_TASK_ROOT}
COPY --from=build /app/package.json package.json
COPY --from=build /app/package-lock.json package-lock.json
COPY --from=build /app/dist .
RUN npm install --production
ENV PORT=5000
EXPOSE 5000
CMD ["index.handler"]