version = 0.1
[default]
[default.build.parameters]
beta_features = true
[default.sync.parameters]
beta_features = true
[default.deploy]
[default.deploy.parameters]
stack_name = "hypocreales"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["Hypocreales=272361327086.dkr.ecr.eu-north-1.amazonaws.com/hypocreales"]
