Transform: AWS::Serverless-2016-10-31
Resources:
  Hypocreales:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        hypocrealesAPI:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          api_key: ""
          MONGO_URL: ""
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: hypocreales-api
      Dockerfile: hypocreales-api/dockerfile
